<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PinkCrab\\WP\\Locations\\' => array($baseDir . '/wp'),
    'PinkCrab\\Locations\\Tests\\' => array($baseDir . '/tests'),
    'PinkCrab\\Locations\\' => array($baseDir . '/src'),
    'PcLocations_001\\eftec\\bladeonehtml\\' => array($vendorDir . '/eftec/bladeonehtml/lib'),
    'PcLocations_001\\eftec\\bladeone\\' => array($vendorDir . '/eftec/bladeone/lib'),
    'PcLocations_001\\Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'PcLocations_001\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'PcLocations_001\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'PcLocations_001\\PinkCrab\\WP_PSR16_Cache\\' => array($vendorDir . '/pinkcrab/wp-psr16-cache/src'),
    'PcLocations_001\\PinkCrab\\Registerables\\' => array($vendorDir . '/pinkcrab/registerables/src'),
    'PcLocations_001\\PinkCrab\\HTTP\\' => array($vendorDir . '/pinkcrab/http/src'),
    'PcLocations_001\\PinkCrab\\Enqueue\\' => array($vendorDir . '/pinkcrab/enqueue/src'),
    'PcLocations_001\\PinkCrab\\Core\\' => array($vendorDir . '/pinkcrab/plugin-framework/src'),
    'PcLocations_001\\PinkCrab\\BladeOne\\' => array($vendorDir . '/pinkcrab/bladeone-provider/src'),
    'PcLocations_001\\Nyholm\\Psr7\\' => array($vendorDir . '/nyholm/psr7/src'),
    'PcLocations_001\\Nyholm\\Psr7Server\\' => array($vendorDir . '/nyholm/psr7-server/src'),
    'PcLocations_001\\Http\\Message\\' => array($vendorDir . '/php-http/message-factory/src'),
    'PcLocations_001\\Dice\\' => array($vendorDir . '/level-2/dice'),
);
